import reflex as rx

class State(rx.State):              #ESTE ES EL STATE SIEMPRE LA HACEMOS COMO UNA CLASE Y MANEJA LOS ESTADOS.
    pass

def index() -> rx.Component:        #ESTE ES EL COMPONENTE GRAFICO
    return rx.text("Hola Reflex", color="blue") #el resto de propiedades lo podemos configurar acá, por ejemplo con el color.

app = rx.App()                      #CON LA VARIABLE APP ES COMO SE GENERA LA APLICACIÖN CON REFLEX Y AHÍ SE AÑADEN LAS PÁGINAS QUE QUERRAMOS.
app.add_page(index)#seleccionamos index que es la página que queremos cargar y luego la compilamos.
app._compile()




#LOS COMPONENTES DE REFLEX ESTAN ENVOLVIENDO LOS DIFERENTES COMPONENTES DE REACT, POR LO TANTO REFLEX USA REACT. LOS COMPONENTES ESTAN FORMADOS POR DOS PARTES BASICAS, LOS CHILDRENS Y LOS PROPS. LOS CHILDREN SON LOS COMPONENTES A LOS QUE SE PUEDE PASAR EL VALOR DEL COMPONENTE O SE LE PUEDE PASAR MAS COMPONENTES. DESPUES ESTAN LAS PROPIEDADES QUE SON ATRIBUTOS QUE AFECTAN EL COMPORTAMIENTO. rx.text("Hello World!", color="blue", font_size="1.5em") EN ESTE CASO "Hello World!" ES EL HIJO MIENTRAS QUE color="blue", font_size="1.5em" SON LAS PROPIEDADES.

#LOS COMPONENTES QUE USA REFLEX NO SON CREADOS POR LA GENTE DE REFLEX SINO QUE ESTAN UTILIZANDO POR DEBAJO COMPONENTES DE REACT, MAS EN CONCRETO COMPONENTES DE CHAKRA UI, CHAKRA UI ES UNA LIBRERIA DE COMPONENTES DE REACT.